### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
trust_remote_code: true
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # ZeRO-3 for full-param

### dataset
dataset: mmfinereason_sft
template: qwen2_vl
cutoff_len: 16384
overwrite_cache: false
preprocessing_num_workers: 16
dataloader_num_workers: 0
seed: 42

### output
output_dir: ../dataflex_saves/Qwen25-VL-7B/icons_full
logging_steps: 10
save_steps: 100
plot_loss: true
save_only_model: false
overwrite_output_dir: true

### wandb
report_to: wandb
run_name: qwen25vl7b_icons_full_123k_3epoch

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### dynamic_train
train_type: dynamic_select
components_cfg_file: src/dataflex/configs/components.yaml
component_name: icons
warmup_step: 10
update_step: 1900
update_times: 2

## eval
eval_dataset: mmfinereason_eval
per_device_eval_batch_size: 1
metric_for_best_model: eval_loss
greater_is_better: false
load_best_model_at_end: false
eval_strategy: steps
eval_steps: 100

# FORCE_TORCHRUN=1 DISABLE_VERSION_CHECK=1 dataflex-cli train examples/train_full/selectors/icons_full.yaml
